parameters: 

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\UserInterface\Api\ImageProcessing\CreateImageProcessing\OperationMapper\OperationMapper:
      arguments:
        $strategies:
          - '@App\UserInterface\Api\ImageProcessing\CreateImageProcessing\OperationMapper\CropOperationMapper'
          - '@App\UserInterface\Api\ImageProcessing\CreateImageProcessing\OperationMapper\ResizeOperationMapper'
          - '@App\UserInterface\Api\ImageProcessing\CreateImageProcessing\OperationMapper\RotateOperationMapper'

    App\Application\ImageProcessing\CreateImageProcessing\OperationMapper\OperationMapper:
      arguments:
        $strategies:
          - '@App\Application\ImageProcessing\CreateImageProcessing\OperationMapper\CropOperationMapper'
          - '@App\Application\ImageProcessing\CreateImageProcessing\OperationMapper\ResizeOperationMapper'
          - '@App\Application\ImageProcessing\CreateImageProcessing\OperationMapper\RotateOperationMapper'

    App\Application\ImageProcessing\ProcessImageProcessing\OperationMapper\OperationDbMapper:
      arguments:
        $strategies:
          - '@App\Application\ImageProcessing\ProcessImageProcessing\OperationMapper\CropDbOperationMapper'
          - '@App\Application\ImageProcessing\ProcessImageProcessing\OperationMapper\ResizeDbOperationMapper'
          - '@App\Application\ImageProcessing\ProcessImageProcessing\OperationMapper\RotateDbOperationMapper'

    App\Infrastructure\Persistence\Rabbitmq\AmqpConnectionFactory:
      arguments:
        $host: '%env(RABBITMQ_HOST)%'
        $port: '%env(int:RABBITMQ_PORT)%'
        $user: '%env(RABBITMQ_USER)%'
        $password: '%env(RABBITMQ_PASSWORD)%'
        $vhost: '%env(RABBITMQ_VHOST)%'

    App\Infrastructure\File\FileStorageService:
      arguments:
        $storagePath: '%kernel.project_dir%/storage/images/originals'

    App\Infrastructure\File\ImageSaver:
      arguments:
        $storagePath: '%kernel.project_dir%/storage/images/processed'

    App\UserInterface\Api\Response\ExceptionListener:
      tags:
        - { name: kernel.event_listener, event: kernel.exception }
